In [5]:
clear


## This is Heading##

In [6]:
name=[1,2,3,54],[2,3,5.]

In [7]:
print(name)

([1, 2, 3, 54], [2, 3, 5])


In [96]:
m=np.mean(array)

In [97]:
print(m
     )

-0.08600427223569307


In [98]:
array=np.random.randn(40,40)

In [99]:
print(array)

[[-0.34913738  0.32663702  1.32069088 ...  1.39445385  0.49786473
   0.87651994]
 [ 0.82227906 -0.53919501  0.04999517 ... -0.11699129  1.22572079
  -1.9652504 ]
 [-0.20250995 -0.39454813 -0.02826193 ... -1.07954511  0.43755315
  -0.70284488]
 ...
 [-1.56909459  1.75860744 -0.07980739 ... -0.0613274   0.93125687
   0.06175419]
 [ 0.51113977 -1.11618408 -1.32415458 ... -1.65066819  0.71950019
  -0.82028373]
 [ 0.67554925  0.0376638   0.43847049 ...  1.25187494  2.41117082
   0.27756008]]


In [101]:
m=np.mean(array)

In [102]:
print(m)

-0.012165283550012078


In [103]:
array=np.random.randn(20)

In [104]:
print(array
     )

[ 0.63280088 -0.41072308 -1.17352973  1.04451933 -0.12023567 -0.01678508
 -0.07469519  0.39309063 -0.13306933  1.58347434  1.23216607  0.47084115
  0.02441124  0.27255739 -0.78834724 -1.32467022  0.35298525  0.70159714
  2.26683896  1.12580518]


In [109]:
type(array)

numpy.ndarray

In [111]:
array.reshape(2,10)

array([[ 0.63280088, -0.41072308, -1.17352973,  1.04451933, -0.12023567,
        -0.01678508, -0.07469519,  0.39309063, -0.13306933,  1.58347434],
       [ 1.23216607,  0.47084115,  0.02441124,  0.27255739, -0.78834724,
        -1.32467022,  0.35298525,  0.70159714,  2.26683896,  1.12580518]])

In [112]:
array.shape

(20,)

In [113]:
array=array.reshape(2,10)

In [114]:
array.shape


(2, 10)

In [119]:
array=array.reshape(1,20)

In [120]:
array.shape

(1, 20)

In [121]:
array=np.random.randn(40)

In [122]:
array.shape

(40,)

In [123]:
array=array.reshape(2,20)

In [124]:
array.shape

(2, 20)

In [125]:
array=array.reshape(40)

In [126]:
array.shape

(40,)

In [127]:
array=array.reshape(4,10)

In [128]:
print(array)

[[-0.48186453  0.2557678   0.28522709  0.41035575 -1.21211858 -1.02151013
   0.58472007  1.21222014 -1.33581091  1.86047458]
 [-0.8535661  -0.93629004  0.00466142  0.24328694 -1.82528122 -0.707184
  -0.47281172  0.56177743  1.12918542  0.09183466]
 [-0.71361242 -1.5763424  -0.50856285 -0.49391902  1.73275816  0.8085193
   0.71692011  1.11294992 -0.42538322  0.52725753]
 [-0.45633412 -1.65378215 -0.25764679  0.11856995 -0.85830066 -0.29973713
   1.7328816   0.47967919 -0.27041782  0.39687952]]


In [129]:
array.shape

(4, 10)

In [131]:
array=np.arange(1,8)

In [132]:
print(array)

[1 2 3 4 5 6 7]


In [137]:
array.shape


(7,)

In [140]:
array=np.arange(1,11)

In [141]:
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [150]:
array=array.reshape(-1,-1)

In [151]:
print(array )

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [154]:
np.random.seed(123)
array=np.random.randint(1,101,10)

In [155]:
print(array)

[67 93 99 18 84 58 87 98 97 48]


In [156]:
array.size

10

In [169]:
array=np.random.randint(1,100,10
                       )

In [170]:
array.size


10

In [173]:
array=array.reshape(2,5)

In [174]:
print(array)

[[78 19 16 28 31]
 [53 71 27 81  7]]


In [175]:
array.size


10

In [176]:
print(array)

[[78 19 16 28 31]
 [53 71 27 81  7]]


In [180]:
print(array[1])

[53 71 27 81  7]


In [183]:
array[0]

array([78, 19, 16, 28, 31])

In [185]:
array[0,1]

19

In [187]:
array[0:3,1]

array([19, 71])

In [188]:
array=np.arange(1,20)

In [189]:
array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [190]:
array[0]

1

In [193]:
array[12]

13

In [194]:
array[-1]

19

In [195]:
array[2:3]

array([3])

In [208]:
array[:-5]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [210]:
matrix=np.arange(1,4)

In [211]:
print(matrix)

[1 2 3]


In [219]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]})

SyntaxError: invalid syntax (<ipython-input-219-a6087bd8e1a1>, line 1)

In [220]:
print(array
     )

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [221]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [226]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [228]:
matrix[0,1]

2

In [230]:
matrix[2,2]

9

In [231]:
matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [233]:
matrix[:2, :2]

array([[1, 2],
       [4, 5]])

In [237]:
matrix[1:, 1:]

array([[5, 6],
       [8, 9]])

In [238]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [240]:
matrix[:2, :2]

array([[1, 2],
       [4, 5]])

In [241]:
matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [242]:
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])

In [247]:
matrix[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [246]:
print(matrix
     )

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [248]:
matrix[0:2,1:]

array([[2, 3],
       [5, 6]])

In [29]:
np.random.seed(123)
matrix2=np.random.randint(1,101,25)


In [30]:
print(matrix2)

[67 93 99 18 84 58 87 98 97 48 74 33 47 97 26 84 79 37 97 81 69 50 56 68
  3]


In [33]:
matrix=np.array([[1,2,3],[4,5,6],[6,85]])

In [34]:
matrix

array([list([1, 2, 3]), list([4, 5, 6]), list([6, 85])], dtype=object)

In [35]:
matrix.shape

(3,)

In [36]:
type(matrix)

numpy.ndarray

In [39]:
np.random.seed(123)
matrix1=np.random.randint(1,12,9)

In [40]:
matrix1=matrix1.reshape(3,3)

In [41]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [42]:
matrix.shape

(3,)

In [46]:
matrix2=np.random.randint(4,88,9)

In [47]:
matrix2=matrix2.reshape(3,3)

In [48]:
matrix2

array([[84, 72, 53],
       [59, 71,  6],
       [43, 70, 51]])

mul=matrix2*matrix1

In [51]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [52]:
matrix2

array([[84, 72, 53],
       [59, 71,  6],
       [43, 70, 51]])

matrix1*matrix2

In [54]:
matrix1 * matrix2

array([[252, 216, 371],
       [118, 284,  66],
       [430, 490, 102]])

In [55]:
matrix1.dot(matrix2)

array([[ 730,  919,  534],
       [ 877, 1198,  691],
       [1339, 1357,  674]])

In [56]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [57]:
np.min(matrix1)

2

In [58]:
np.max(matrix1)

11

In [59]:
np.argmin(matrix1)

3

In [60]:
np.argmax(matrix1)

5

In [61]:
matrix

array([list([1, 2, 3]), list([4, 5, 6]), list([6, 85])], dtype=object)

In [62]:
np.exp(matrix1)

array([[2.00855369e+01, 2.00855369e+01, 1.09663316e+03],
       [7.38905610e+00, 5.45981500e+01, 5.98741417e+04],
       [2.20264658e+04, 1.09663316e+03, 7.38905610e+00]])

In [63]:
np.sin(100)

-0.5063656411097588

In [64]:
np.cos(0
      )

1.0

In [67]:
m=np.linspace(1,5,100)

In [68]:
print(m)

[1.         1.04040404 1.08080808 1.12121212 1.16161616 1.2020202
 1.24242424 1.28282828 1.32323232 1.36363636 1.4040404  1.44444444
 1.48484848 1.52525253 1.56565657 1.60606061 1.64646465 1.68686869
 1.72727273 1.76767677 1.80808081 1.84848485 1.88888889 1.92929293
 1.96969697 2.01010101 2.05050505 2.09090909 2.13131313 2.17171717
 2.21212121 2.25252525 2.29292929 2.33333333 2.37373737 2.41414141
 2.45454545 2.49494949 2.53535354 2.57575758 2.61616162 2.65656566
 2.6969697  2.73737374 2.77777778 2.81818182 2.85858586 2.8989899
 2.93939394 2.97979798 3.02020202 3.06060606 3.1010101  3.14141414
 3.18181818 3.22222222 3.26262626 3.3030303  3.34343434 3.38383838
 3.42424242 3.46464646 3.50505051 3.54545455 3.58585859 3.62626263
 3.66666667 3.70707071 3.74747475 3.78787879 3.82828283 3.86868687
 3.90909091 3.94949495 3.98989899 4.03030303 4.07070707 4.11111111
 4.15151515 4.19191919 4.23232323 4.27272727 4.31313131 4.35353535
 4.39393939 4.43434343 4.47474747 4.51515152 4.55555556 4.595959

In [69]:
type(m)

numpy.ndarray

In [70]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [71]:
matrix1.dtype='bool'

In [72]:
matrix1

array([[ True, False, False, False,  True, False, False, False,  True,
        False, False, False],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False]])

In [73]:
np.random.seed(123)
matrix=np.random.randint(1,11,9)

In [74]:
matrix=matrix.reshape(3,3
                     )

In [75]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [77]:
np.sum(matrix)

39

In [78]:
np.min(matrix, axis=1)

array([3, 2, 1])

In [79]:
np.sum(matrix, axis=1)

array([13, 16, 10])

In [80]:
np.sum(matrix)

39

In [81]:
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [82]:
np.cumsum(matrix, axis=1)

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]], dtype=int32)

In [83]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [84]:
np.cumsum(matrix, axis=0)

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]], dtype=int32)

In [85]:
np.product(matrix, axis=0)

array([42, 24, 70])

In [86]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [87]:
np.random.shuffle(array)

In [88]:
array

array([ 7, 24,  7, 12, 18,  5,  1, 28,  3, 12, 22])

In [89]:
array

array([ 7, 24,  7, 12, 18,  5,  1, 28,  3, 12, 22])

In [90]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [91]:
np.random.shuffle(matrix)

In [92]:
matrix

array([[ 2,  4, 10],
       [ 7,  2,  1],
       [ 3,  3,  7]])

In [93]:
np.unique(matrix)

array([ 1,  2,  3,  4,  7, 10])

In [94]:
np.unique(array).size

9

In [96]:
np.unique(matrix)

array([ 1,  2,  3,  4,  7, 10])

In [97]:
np.unique(matrix, return_index=True, return_counts=True)

(array([ 1,  2,  3,  4,  7, 10]),
 array([5, 0, 6, 1, 3, 2], dtype=int64),
 array([1, 2, 2, 1, 2, 1], dtype=int64))

In [98]:
matrix

array([[ 2,  4, 10],
       [ 7,  2,  1],
       [ 3,  3,  7]])

In [99]:
np.random.seed(123)

In [100]:
np.random.seed(123)
np.random.randint(1,99,9).reshape(3,3)

array([[67, 93, 18],
       [84, 58, 87],
       [98, 97, 48]])

In [101]:
np.random.seed(123)
matrix1=np.random.randint(1,99,9).reshape(3,3)
matrix2=np.random.randint(1,44,9).reshape(3,3)


In [102]:
matrix1

array([[67, 93, 18],
       [84, 58, 87],
       [98, 97, 48]])

In [103]:
matrix2

array([[10, 33, 33],
       [26, 20, 15],
       [37, 33, 17]])

In [104]:
np.hstack((matrix1,matrix2))

array([[67, 93, 18, 10, 33, 33],
       [84, 58, 87, 26, 20, 15],
       [98, 97, 48, 37, 33, 17]])

In [105]:
np.vstack((matrix1,matrix2))

array([[67, 93, 18],
       [84, 58, 87],
       [98, 97, 48],
       [10, 33, 33],
       [26, 20, 15],
       [37, 33, 17]])

In [106]:
movies_data=pd.read_csv("imdb_5000_movies.csv
                        ")

SyntaxError: EOL while scanning string literal (<ipython-input-106-3576977933c8>, line 1)

In [107]:
import pandas as pd


In [191]:
print(movies_data)

         budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.

In [111]:
type(movies_data)

pandas.core.frame.DataFrame

In [112]:
movies_data

budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4     [{"id": 818, "name": "based on novel"}, {"id":...                en   
...                                                 ...               ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...                es   
4799                                                 []                en   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en   
4801                                                 []                en   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577   
1     Captain Barbossa, long believed to be dead, ha...  139.082615   
2     A cryptic message from Bond’s past sends him o...  107.376788   
3     Following the death of District Attorney Harve...  112.312950   
4     John Carter is a war-weary, former military ca...   43.926995   
...                                                 ...         ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ... 

In [113]:
movies_data.shape

(4803, 20)

In [114]:
movies_data.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [115]:
movies_data.index

RangeIndex(start=0, stop=4803, step=1)

In [116]:
np.movies_data(:1)

SyntaxError: invalid syntax (<ipython-input-116-4e0810d4eeed>, line 1)

In [117]:
np.movies_data(1,44)

AttributeError: module 'numpy' has no attribute 'movies_data'

In [118]:
np.shuffle(movies_data)

AttributeError: module 'numpy' has no attribute 'shuffle'

In [119]:
matrix


array([[ 2,  4, 10],
       [ 7,  2,  1],
       [ 3,  3,  7]])

In [121]:
movies_data.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [122]:
movies_data.index

RangeIndex(start=0, stop=4803, step=1)

In [123]:
movies_data.head

<bound method NDFrame.head of          budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   1999

In [124]:
movies_data.tail

<bound method NDFrame.tail of          budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   1999

In [126]:
movies_data.head(15)

budget                                             genres  \
0   237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1   300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2   245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3   250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4   260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
5   258000000  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...   
6   260000000  [{"id": 16, "name": "Animation"}, {"id": 10751...   
7   280000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
8   250000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
9   250000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
10  270000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
11  200000000  [{"id": 12, "name": "Adventure"}, {"id": 28, "...   
12  200000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
13  255000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
14  225000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                             homepage      id  \
0                         http://www.avatarmovie.com/   19995   
1        http://disney.go.com/disneypictures/pirates/     285   
2         http://www.sonypictures.com/movies/spectre/  206647   
3                  http://www.thedarkknightrises.com/   49026   
4                http://movies.disney.com/john-carter   49529   
5     http://www.sonypictures.com/movies/spider-man3/     559   
6        http://disney.go.com/disneypictures/tangled/   38757   
7   http://marvel.com/movies/movie/193/avengers_ag...   99861   
8   http://harrypotter.warnerbros.com/harrypottera...     767   
9        http://www.batmanvsupermandawnofjustice.com/  209112   
10                            http://www.superman.com    1452   
11  http://www.mgm.com/view/movie/234/Quantum-of-S...   10764   
12       http://disney.go.com/disneypictures/pirates/      58   
13              http://disney.go.com/the-lone-ranger/   57201   
14                         http://www.manofsteel.com/   49521   

                                             keywords original_language  \
0   [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1   [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2   [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3   [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4   [{"id": 818, "name": "based on novel"}, {"id":...                en   
5   [{"id": 851, "name": "dual identity"}, {"id": ...                en   
6   [{"id": 1562, "name": "hostage"}, {"id": 2343,...                en   
7   [{"id": 8828, "name": "marvel comic"}, {"id": ...                en   
8   [{"id": 616, "name": "witch"}, {"id": 2343, "n...                en   
9   [{"id": 849, "name": "dc comics"}, {"id": 7002...                en   
10  [{"id": 83, "name": "saving the world"}, {"id"...                en   
11  [{"id": 627, "name": "killing"}, {"id": 1568, ...                en   
12  [{"id": 616, "name": "witch"}, {"id": 663, "na...                en   
13  [{"id": 1556, "name": "texas"}, {"id": 2673, "...                en   
14  [{"id": 83, "name": "saving the world"}, {"id"...                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
5                                 Spider-Man 3   
6                                      Tangled   
7                      Avengers: Age of Ultron   
8       Harry Potter and the Half-Blood Prince   
9           Batman v Superman: Dawn of Justice   
10                            Superman Returns   
11                           Quantum of Solace   
12  Pirates of the Caribbe

In [128]:
 movies_data.head(1)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title  vote_average  vote_count  
0  Enter the World of Pandora.  Avatar           7.2       11800

In [129]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [131]:
movies_data.describe()

budget             id   popularity       revenue      runtime  \
count  4.803000e+03    4803.000000  4803.000000  4.803000e+03  4801.000000   
mean   2.904504e+07   57165.484281    21.492301  8.226064e+07   106.875859   
std    4.072239e+07   88694.614033    31.816650  1.628571e+08    22.611935   
min    0.000000e+00       5.000000     0.000000  0.000000e+00     0.000000   
25%    7.900000e+05    9014.500000     4.668070  0.000000e+00    94.000000   
50%    1.500000e+07   14629.000000    12.921594  1.917000e+07   103.000000   
75%    4.000000e+07   58610.500000    28.313505  9.291719e+07   118.000000   
max    3.800000e+08  459488.000000   875.581305  2.787965e+09   338.000000   

       vote_average    vote_count  
count   4803.000000   4803.000000  
mean       6.092172    690.217989  
std        1.194612   1234.585891  
min        0.000000      0.000000  
25%        5.600000     54.000000  
50%        6.200000    235.000000  
75%        6.800000    737.000000  
max       10.000000  13752.000000

movies_data.head()

In [132]:
movies_data.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [134]:
movies_data['budget', ]

KeyError: ('budget',)

In [138]:
movies_data[['budget','genres']]

budget                                             genres
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
...         ...                                                ...
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801          0                                                 []
4802          0                [{"id": 99, "name": "Documentary"}]

[4803 rows x 2 columns]

In [143]:
m=movies_data[['budget']]

In [144]:
type(m)

pandas.core.frame.DataFrame

In [146]:
print(m)

         budget
0     237000000
1     300000000
2     245000000
3     250000000
4     260000000
...         ...
4798     220000
4799       9000
4800          0
4801          0
4802          0

[4803 rows x 1 columns]


In [148]:
movies_data[['original_title','genres','vote_average']].head(5)

original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                              genres  vote_average  
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2  
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9  
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3  
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6  
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1

In [152]:
movies_data[['original_title','budget']]

original_title     budget
0                                       Avatar  237000000
1     Pirates of the Caribbean: At World's End  300000000
2                                      Spectre  245000000
3                        The Dark Knight Rises  250000000
4                                  John Carter  260000000
...                                        ...        ...
4798                               El Mariachi     220000
4799                                 Newlyweds       9000
4800                 Signed, Sealed, Delivered          0
4801                          Shanghai Calling          0
4802                         My Date with Drew          0

[4803 rows x 2 columns]

In [154]:
m=movies_data[2:5]

In [155]:
print(m)

      budget                                             genres  \
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                      homepage      id  \
2  http://www.sonypictures.com/movies/spectre/  206647   
3           http://www.thedarkknightrises.com/   49026   
4         http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

          original_title                                           overview  \
2                Spectre  A cryptic message from Bond’s past sends him o...   
3  The Dark Knight Rises  Following the dea

In [156]:
type(m)

pandas.core.frame.DataFrame

In [158]:
m[['genres']]

genres
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...

In [159]:
movies_data

budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4     [{"id": 818, "name": "based on novel"}, {"id":...                en   
...                                                 ...               ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...                es   
4799                                                 []                en   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en   
4801                                                 []                en   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577   
1     Captain Barbossa, long believed to be dead, ha...  139.082615   
2     A cryptic message from Bond’s past sends him o...  107.376788   
3     Following the death of District Attorney Harve...  112.312950   
4     John Carter is a war-weary, former military ca...   43.926995   
...                                                 ...         ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ... 

In [160]:
m=movies_data.head(5)

In [161]:
print(m)

      budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "nam

In [192]:
movies_data.loc(3)

ValueError: No axis named 3 for object type <class 'pandas.core.frame.DataFrame'>

movies_data=pd.read_csv("tmdb_5000_movies.csv")


In [195]:
movies_data=pd.read_csv("tmdb_5000_movies.csv", index_col='original_title')

In [196]:
movies_data

budget  \
original_title                                        
Avatar                                    237000000   
Pirates of the Caribbean: At World's End  300000000   
Spectre                                   245000000   
The Dark Knight Rises                     250000000   
John Carter                               260000000   
...                                             ...   
El Mariachi                                  220000   
Newlyweds                                      9000   
Signed, Sealed, Delivered                         0   
Shanghai Calling                                  0   
My Date with Drew                                 0   

                                                                                     genres  \
original_title                                                                                
Avatar                                    [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
Pirates of the Caribbean: At World's End  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
Spectre                                   [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
The Dark Knight Rises                     [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
John Carter                               [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...                                                                                     ...   
El Mariachi                               [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
Newlyweds                                 [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
Signed, Sealed, Delivered                 [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
Shanghai Calling                                                                         []   
My Date with Drew                                       [{"id": 99, "name": "Documentary"}]   

                                                                                   homepage  \
original_title                                                                                
Avatar                                                          http://www.avatarmovie.com/   
Pirates of the Caribbean: At World's End       http://disney.go.com/disneypictures/pirates/   
Spectre                                         http://www.sonypictures.com/movies/spectre/   
The Dark Knight Rises                                    http://www.thedarkknightrises.com/   
John Carter                                            http://movies.disney.com/john-carter   
...                                                                                     ...   
El Mariachi                                                                             NaN   
Newlyweds                                                                               NaN   
Signed, Sealed, Delivered                 http://www.hallmarkchannel.com/signedsealeddel...   
Shanghai Calling                                                http://shanghaicalling.com/   
My Date with Drew                                                                       NaN   

                                              id  \
original_title                                     
Avatar                                     19995   
Pirates of the Caribbean: At World's End     285   
Spectre                                   206647   
The Dark Knight Rises                      49026   
John Carter                                49529   
...                                          ...   
El Mariachi                                 9367   
Newlyweds                                  72766   
Signed, Sealed, Delivered                 231617   
Shanghai Calling                          126186   
My Date with Drew                          25975   

                                                                                   keywords  \
original_title                                                                       

In [202]:
m=movies_data.loc['Avatar','Spectre'],['budget']

KeyError: 'Spectre'

In [200]:
print(m)

budget                                                          237000000
genres                  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
homepage                                      http://www.avatarmovie.com/
id                                                                  19995
keywords                [{"id": 1463, "name": "culture clash"}, {"id":...
original_language                                                      en
overview                In the 22nd century, a paraplegic Marine is di...
popularity                                                        150.438
production_companies    [{"name": "Ingenious Film Partners", "id": 289...
production_countries    [{"iso_3166_1": "US", "name": "United States o...
release_date                                                   2009-12-10
revenue                                                        2787965087
runtime                                                               162
spoken_languages        [{"iso_639_1":

In [204]:
movies_data=pd.read_csv("imbd_5000_movies.csv")

FileNotFoundError: [Errno 2] File imbd_5000_movies.csv does not exist: 'imbd_5000_movies.csv'

In [206]:
movies_data.head(5)

budget  \
original_title                                        
Avatar                                    237000000   
Pirates of the Caribbean: At World's End  300000000   
Spectre                                   245000000   
The Dark Knight Rises                     250000000   
John Carter                               260000000   

                                                                                     genres  \
original_title                                                                                
Avatar                                    [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
Pirates of the Caribbean: At World's End  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
Spectre                                   [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
The Dark Knight Rises                     [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
John Carter                               [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                                                              homepage  \
original_title                                                                           
Avatar                                                     http://www.avatarmovie.com/   
Pirates of the Caribbean: At World's End  http://disney.go.com/disneypictures/pirates/   
Spectre                                    http://www.sonypictures.com/movies/spectre/   
The Dark Knight Rises                               http://www.thedarkknightrises.com/   
John Carter                                       http://movies.disney.com/john-carter   

                                              id  \
original_title                                     
Avatar                                     19995   
Pirates of the Caribbean: At World's End     285   
Spectre                                   206647   
The Dark Knight Rises                      49026   
John Carter                                49529   

                                                                                   keywords  \
original_title                                                                                
Avatar                                    [{"id": 1463, "name": "culture clash"}, {"id":...   
Pirates of the Caribbean: At World's End  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
Spectre                                   [{"id": 470, "name": "spy"}, {"id": 818, "name...   
The Dark Knight Rises                     [{"id": 849, "name": "dc comics"}, {"id": 853,...   
John Carter                               [{"id": 818, "name": "based on novel"}, {"id":...   

                                         original_language  \
original_title                                               
Avatar                                                  en   
Pirates of the Caribbean: At World's End                en   
Spectre                                                 en   
The Dark Knight Rises                                   en   
John Carter                                             en   

                                                                                   overview  \
original_title                                                                                
Avatar                                    In the 22nd century, a paraplegic Marine is di...   
Pirates of the Caribbean: At World's End  Captain Barbossa, long believed to be dead, ha...   
Spectre                                   A cryptic message from Bond’s past sends him o...   
The Dark Knight Rises                     Following the death of District Attorney Harve...   
John Carter                               John Carter is a war-weary, former military ca...   

                                          popularity  \
original_title                                         
Avatar                                    150.437577   
Pirates of the Caribbean: At World's End  139.082615   
Spectr

In [207]:
movies_data.head()

budget  \
original_title                                        
Avatar                                    237000000   
Pirates of the Caribbean: At World's End  300000000   
Spectre                                   245000000   
The Dark Knight Rises                     250000000   
John Carter                               260000000   

                                                                                     genres  \
original_title                                                                                
Avatar                                    [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
Pirates of the Caribbean: At World's End  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
Spectre                                   [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
The Dark Knight Rises                     [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
John Carter                               [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                                                              homepage  \
original_title                                                                           
Avatar                                                     http://www.avatarmovie.com/   
Pirates of the Caribbean: At World's End  http://disney.go.com/disneypictures/pirates/   
Spectre                                    http://www.sonypictures.com/movies/spectre/   
The Dark Knight Rises                               http://www.thedarkknightrises.com/   
John Carter                                       http://movies.disney.com/john-carter   

                                              id  \
original_title                                     
Avatar                                     19995   
Pirates of the Caribbean: At World's End     285   
Spectre                                   206647   
The Dark Knight Rises                      49026   
John Carter                                49529   

                                                                                   keywords  \
original_title                                                                                
Avatar                                    [{"id": 1463, "name": "culture clash"}, {"id":...   
Pirates of the Caribbean: At World's End  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
Spectre                                   [{"id": 470, "name": "spy"}, {"id": 818, "name...   
The Dark Knight Rises                     [{"id": 849, "name": "dc comics"}, {"id": 853,...   
John Carter                               [{"id": 818, "name": "based on novel"}, {"id":...   

                                         original_language  \
original_title                                               
Avatar                                                  en   
Pirates of the Caribbean: At World's End                en   
Spectre                                                 en   
The Dark Knight Rises                                   en   
John Carter                                             en   

                                                                                   overview  \
original_title                                                                                
Avatar                                    In the 22nd century, a paraplegic Marine is di...   
Pirates of the Caribbean: At World's End  Captain Barbossa, long believed to be dead, ha...   
Spectre                                   A cryptic message from Bond’s past sends him o...   
The Dark Knight Rises                     Following the death of District Attorney Harve...   
John Carter                               John Carter is a war-weary, former military ca...   

                                          popularity  \
original_title                                         
Avatar                                    150.437577   
Pirates of the Caribbean: At World's End  139.082615   
Spectr

In [208]:
movies

NameError: name 'movies' is not defined

In [211]:
n=movies_data['runtime']

In [212]:
print(n)

original_title
Avatar                                      162.0
Pirates of the Caribbean: At World's End    169.0
Spectre                                     148.0
The Dark Knight Rises                       165.0
John Carter                                 132.0
                                            ...  
El Mariachi                                  81.0
Newlyweds                                    85.0
Signed, Sealed, Delivered                   120.0
Shanghai Calling                             98.0
My Date with Drew                            90.0
Name: runtime, Length: 4803, dtype: float64


In [214]:
n.size()

TypeError: 'int' object is not callable

In [215]:
n.count()

4801

In [216]:
n.size()

TypeError: 'int' object is not callable

In [217]:
n.size

4803

In [218]:
n.min()

0.0

In [219]:
n.max()

338.0

In [220]:
n.mean()

106.87585919600083

In [221]:
n.std()

22.611934588844207

In [222]:
n.unique()

array([162., 169., 148., 165., 132., 139., 100., 141., 153., 151., 154.,
       106., 149., 143., 150., 136., 144., 140., 161., 113., 187., 194.,
       147., 131., 124., 127., 130., 108., 104., 142., 125., 114., 103.,
       115., 137., 116., 122.,  93.,  98.,  91., 158.,  96., 109., 152.,
        94., 126., 112., 123., 135., 118.,  97., 119., 102., 120., 121.,
       166.,  99., 183., 175., 138., 157.,  92., 101., 111.,  89., 105.,
       107., 129.,  88.,  85., 163., 133.,  95.,  90., 110., 128., 156.,
       117., 146.,  82.,  78., 134., 170.,  76., 178.,  84., 155., 145.,
       180., 172., 167., 201., 179.,  83.,  87.,  80.,  74.,  81., 177.,
        86., 164., 159., 191., 189., 214.,   0.,  75., 192., 160., 219.,
       248., 188., 202., 173., 195.,  77.,  79.,  63., 229., 193., 254.,
        72.,  68., 199., 181., 242., 338.,  73., 216., 276.,  nan, 200.,
        69., 197., 184., 176., 185., 171., 174.,  46.,  53.,  42., 240.,
        41.,  67., 238., 186.,  70.,  14., 225., 20

In [224]:
n.nunique()

156

In [227]:
type(n.unique())

numpy.ndarray

In [229]:
n.value.count()

AttributeError: 'Series' object has no attribute 'value'

In [230]:
n.value_counts()

90.0     163
100.0    149
98.0     140
97.0     133
95.0     123
        ... 
338.0      1
53.0       1
214.0      1
194.0      1
179.0      1
Name: runtime, Length: 156, dtype: int64

In [233]:
n.value_counts(ascending = False)

90.0     163
100.0    149
98.0     140
97.0     133
95.0     123
        ... 
338.0      1
53.0       1
214.0      1
194.0      1
179.0      1
Name: runtime, Length: 156, dtype: int64

In [234]:
n.value_counts(ascending =False, bins=3)

(-0.339, 112.667]     3245
(112.667, 225.333]    1548
(225.333, 338.0]         8
Name: runtime, dtype: int64

In [235]:
movies_data['budget']

original_title
Avatar                                      237000000
Pirates of the Caribbean: At World's End    300000000
Spectre                                     245000000
The Dark Knight Rises                       250000000
John Carter                                 260000000
                                              ...    
El Mariachi                                    220000
Newlyweds                                        9000
Signed, Sealed, Delivered                           0
Shanghai Calling                                    0
My Date with Drew                                   0
Name: budget, Length: 4803, dtype: int64

In [236]:
anime=['A','b','bha','f','asdfsa','Asad']

In [239]:
series=pd.Series(anime, name='Genre')

In [240]:
series

0         A
1         b
2       bha
3         f
4    asdfsa
5      Asad
Name: Genre, dtype: object

In [251]:
genre=['name1','name2','name3','name4','name5','name6']

In [252]:
sereies2=pd.Series(anime, index=genre, name='practice')

In [253]:
sereies2

name1         A
name2         b
name3       bha
name4         f
name5    asdfsa
name6      Asad
Name: practice, dtype: object

In [255]:
movies_data['runtime'].head(5)

original_title
Avatar                                      162.0
Pirates of the Caribbean: At World's End    169.0
Spectre                                     148.0
The Dark Knight Rises                       165.0
John Carter                                 132.0
Name: runtime, dtype: float64

In [274]:
m=movies_data['runtime'].head(10)

In [278]:
m.nsmallest(n=1)

original_title
Tangled    100.0
Name: runtime, dtype: float64

In [279]:
m.nlargest()

original_title
Pirates of the Caribbean: At World's End    169.0
The Dark Knight Rises                       165.0
Avatar                                      162.0
Harry Potter and the Half-Blood Prince      153.0
Batman v Superman: Dawn of Justice          151.0
Name: runtime, dtype: float64

In [280]:
m.idxmin()

'Tangled'

In [282]:
m.idxmax()

"Pirates of the Caribbean: At World's End"

In [288]:
pd.read_csv('imbd_5000_movies.csv')

FileNotFoundError: [Errno 2] File imbd_5000_movies.csv does not exist: 'imbd_5000_movies.csv'

In [290]:
m=pd.read_csv('tmdb_5000_movies.csv', index_col='original_title')

In [294]:
movies.reset_index()

NameError: name 'movies' is not defined

In [296]:
m.reset_index()

original_title     budget  \
0                                       Avatar  237000000   
1     Pirates of the Caribbean: At World's End  300000000   
2                                      Spectre  245000000   
3                        The Dark Knight Rises  250000000   
4                                  John Carter  260000000   
...                                        ...        ...   
4798                               El Mariachi     220000   
4799                                 Newlyweds       9000   
4800                 Signed, Sealed, Delivered          0   
4801                          Shanghai Calling          0   
4802                         My Date with Drew          0   

                                                 genres  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...                                                 ...   
4798  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801                                                 []   
4802                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4     [{"id": 818, "name": "based on novel"}, {"id":...                en   
...                                                 ...               ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...                es   
4799                                                 []                en   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en   
4801                                                 []                en   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en   

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577   
1     Captain Barbossa, long believed to be dead, ha...  139.082615   
2     A cryptic message from Bond’s past sends him o...  107.376788   
3     Following the death of District Attorney Harve...  112.312950   
4     John Carter is a war-weary, former military ca...   43.926995   
...                                                 ...         ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ...    1.929883   

       

In [297]:
m.reset_index(inplace=True)

In [299]:
print(m)

                                original_title     budget  \
0                                       Avatar  237000000   
1     Pirates of the Caribbean: At World's End  300000000   
2                                      Spectre  245000000   
3                        The Dark Knight Rises  250000000   
4                                  John Carter  260000000   
...                                        ...        ...   
4798                               El Mariachi     220000   
4799                                 Newlyweds       9000   
4800                 Signed, Sealed, Delivered          0   
4801                          Shanghai Calling          0   
4802                         My Date with Drew          0   

                                                 genres  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     [{"id": 28, "name": "Acti

In [301]:
m.set_index('original_title', inplace=True)

In [302]:
print(m)

                                             budget  \
original_title                                        
Avatar                                    237000000   
Pirates of the Caribbean: At World's End  300000000   
Spectre                                   245000000   
The Dark Knight Rises                     250000000   
John Carter                               260000000   
...                                             ...   
El Mariachi                                  220000   
Newlyweds                                      9000   
Signed, Sealed, Delivered                         0   
Shanghai Calling                                  0   
My Date with Drew                                 0   

                                                                                     genres  \
original_title                                                                                
Avatar                                    [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

In [303]:
m.reset_index(inplace=True)

In [305]:
m.index

RangeIndex(start=0, stop=4803, step=1)

In [311]:
print(m.columns)

Index(['original_title', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')


In [313]:
movies_data.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [318]:
movies

NameError: name 'movies' is not defined

In [322]:
movies_data.index.get_loc('Spectre')

2

In [328]:
movies_data.index.is_unique

False

In [329]:
xyz=pd.index(['A','b','c','d'])

AttributeError: module 'pandas' has no attribute 'index'

In [331]:
sus=pd.read_csv('master.csv')

In [333]:
sus


country  year     sex          age  suicides_no  population  \
0         Albania  1987    male  15-24 years           21      312900   
1         Albania  1987    male  35-54 years           16      308000   
2         Albania  1987  female  15-24 years           14      289700   
3         Albania  1987    male    75+ years            1       21800   
4         Albania  1987    male  25-34 years            9      274300   
...           ...   ...     ...          ...          ...         ...   
27815  Uzbekistan  2014  female  35-54 years          107     3620833   
27816  Uzbekistan  2014  female    75+ years            9      348465   
27817  Uzbekistan  2014    male   5-14 years           60     2762158   
27818  Uzbekistan  2014  female   5-14 years           44     2631600   
27819  Uzbekistan  2014  female  55-74 years           21     1438935   

       suicides/100k pop    country-year  HDI for year  gdp_for_year ($)   \
0                   6.71     Albania1987           NaN      2,156,624,900   
1                   5.19     Albania1987           NaN      2,156,624,900   
2                   4.83     Albania1987           NaN      2,156,624,900   
3                   4.59     Albania1987           NaN      2,156,624,900   
4                   3.28     Albania1987           NaN      2,156,624,900   
...                  ...             ...           ...                ...   
27815               2.96  Uzbekistan2014         0.675     63,067,077,179   
27816               2.58  Uzbekistan2014         0.675     63,067,077,179   
27817               2.17  Uzbekistan2014         0.675     63,067,077,179   
27818               1.67  Uzbekistan2014         0.675     63,067,077,179   
27819               1.46  Uzbekistan2014         0.675     63,067,077,179   

       gdp_per_capita ($)       generation  
0                     796     Generation X  
1                     796           Silent  
2                     796     Generation X  
3                     796  G.I. Generation  
4                     796          Boomers  
...                   ...              ...  
27815                2309     Generation X  
27816                2309           Silent  
27817                2309     Generation Z  
27818                2309     Generation Z  
27819                2309          Boomers  

[27820 rows x 12 columns]

In [334]:
sus.country

0           Albania
1           Albania
2           Albania
3           Albania
4           Albania
            ...    
27815    Uzbekistan
27816    Uzbekistan
27817    Uzbekistan
27818    Uzbekistan
27819    Uzbekistan
Name: country, Length: 27820, dtype: object

In [336]:
sus.country.unique()

array(['Albania', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Barbados', 'Belarus', 'Belgium', 'Belize',
       'Bosnia and Herzegovina', 'Brazil', 'Bulgaria', 'Cabo Verde',
       'Canada', 'Chile', 'Colombia', 'Costa Rica', 'Croatia', 'Cuba',
       'Cyprus', 'Czech Republic', 'Denmark', 'Dominica', 'Ecuador',
       'El Salvador', 'Estonia', 'Fiji', 'Finland', 'France', 'Georgia',
       'Germany', 'Greece', 'Grenada', 'Guatemala', 'Guyana', 'Hungary',
       'Iceland', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Kazakhstan', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Latvia',
       'Lithuania', 'Luxembourg', 'Macau', 'Maldives', 'Malta',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Norway', 'Oman', 'Panama', 'Paraguay',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Republic of Korea', 'Romania', '

In [339]:
sus.country=='Israel'

0        False
1        False
2        False
3        False
4        False
         ...  
27815    False
27816    False
27817    False
27818    False
27819    False
Name: country, Length: 27820, dtype: bool

In [344]:
sus[sus.country=='Israel']

country  year     sex          age  suicides_no  population  \
12416  Israel  1985    male    75+ years           24       66600   
12417  Israel  1985    male  55-74 years           48      249100   
12418  Israel  1985  female    75+ years           10       75500   
12419  Israel  1985    male  35-54 years           41      396400   
12420  Israel  1985  female  55-74 years           28      290900   
...       ...   ...     ...          ...          ...         ...   
12783  Israel  2015  female  25-34 years           13      581972   
12784  Israel  2015  female  35-54 years           20      967412   
12785  Israel  2015  female  15-24 years            8      617440   
12786  Israel  2015    male   5-14 years            2      770443   
12787  Israel  2015  female   5-14 years            1      733603   

       suicides/100k pop country-year  HDI for year  gdp_for_year ($)   \
12416              36.04   Israel1985         0.768     27,493,591,484   
12417              19.27   Israel1985         0.768     27,493,591,484   
12418              13.25   Israel1985         0.768     27,493,591,484   
12419              10.34   Israel1985         0.768     27,493,591,484   
12420               9.63   Israel1985         0.768     27,493,591,484   
...                  ...          ...           ...                ...   
12783               2.23   Israel2015           NaN    299,093,839,690   
12784               2.07   Israel2015           NaN    299,093,839,690   
12785               1.30   Israel2015           NaN    299,093,839,690   
12786               0.26   Israel2015           NaN    299,093,839,690   
12787               0.14   Israel2015           NaN    299,093,839,690   

       gdp_per_capita ($)       generation  
12416                7325  G.I. Generation  
12417                7325  G.I. Generation  
12418                7325  G.I. Generation  
12419                7325           Silent  
12420                7325  G.I. Generation  
...                   ...              ...  
12783               39793       Millenials  
12784               39793     Generation X  
12785               39793       Millenials  
12786               39793     Generation Z  
12787               39793     Generation Z  

[372 rows x 12 columns]

In [370]:
mask1=sus.country=='Israel'
mask2=sus.year== 2014
mask3=sus.year==2015
m=sus.loc[mask1 & (mask2 | mask3)]
m=
print(m)

Empty DataFrame
Columns: [country, year, sex, age, suicides_no, population, suicides/100k pop, country-year, HDI for year,  gdp_for_year ($) , gdp_per_capita ($), generation]
Index: []


In [ ]:
maks1