In [111]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold #same as KFOLD but split  data in uniform order
from sklearn.model_selection import cross_val_score

In [10]:
digits=load_digits()

In [82]:
dir(digits)


['DESCR', 'data', 'images', 'target', 'target_names']

In [29]:
Xtrain,Xtest,ytrain,ytest=train_test_split(digits.data,digits.target, test_size=0.2,random_state=10)

In [30]:
logreg=LogisticRegression()
tree=DecisionTreeClassifier()
rf=RandomForestClassifier()
svm=SVC()

In [85]:
logreg.fit(Xtrain,ytrain)
tree.fit(Xtrain,ytrain)
rf.fit(Xtrain,ytrain)
svm.fit(Xtrain,ytrain)



C:\Users\ZEESHAN123\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [36]:
print(f"Score of LogisticRegression:{logreg.score(Xtest,ytest)}\nSocre of tree:{tree.score(Xtest,ytest)}\nScore of RandomForest:{rf.score(Xtest,ytest)}\nScore of SVM:{svm.score(Xtest,ytest)}")

Score of LogisticRegression:0.95
Socre of tree:0.8555555555555555
Score of RandomForest:0.9694444444444444
Score of SVM:0.9833333333333333


In [43]:
kf=KFold(n_splits=3, shuffle=False, random_state=None)


In [64]:
for train_sample,test_sample in kf.split([19,872,63,4,9875,6,7,98,880]):  #This is how KFOLD splits data#Its is giving 
    print(train_sample,test_sample)                                       #Index of data.How the split data ,showing index

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [41]:
def get_score(model,Xtrain,Xtest,ytrain,ytest):
    model.fit(Xtrain,ytrain)
    return  model.score(Xtest,ytest)

In [114]:
fold=StratifiedKFold(n_splits=3)#Same as KFold but splits data in uniformed way therefore much better to compare results
for train_index,test_index in kf.split(digits.data):  
    score_log=[]
    score_svm=[]
    score_rf=[]
    Xtrain=digits.data[train_index]
    Xtest=digits.data[test_index]
    ytrain=digits.target[train_index]
    ytest=digits.target[test_index]
    print(f"1-LogisitcRegression Score:{get_score(LogisticRegression(),Xtrain,Xtest,ytrain,ytest)}")
    print(f"2-SVM Score:{get_score(SVC(),Xtrain,Xtest,ytrain,ytest)}")
    print(f"3-RandomForest Score:{get_score(RandomForestClassifier(),Xtrain,Xtest,ytrain,ytest)}")

    
    

C:\Users\ZEESHAN123\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


1-LogisitcRegression Score:0.9232053422370617
2-SVM Score:0.9666110183639399
3-RandomForest Score:0.9332220367278798
1-LogisitcRegression Score:0.9415692821368948
2-SVM Score:0.9816360601001669


C:\Users\ZEESHAN123\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


3-RandomForest Score:0.9482470784641068
1-LogisitcRegression Score:0.9148580968280468


C:\Users\ZEESHAN123\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


2-SVM Score:0.9549248747913188
3-RandomForest Score:0.9248747913188647


In [113]:
cross_val_score(SVC(),digits.data,digits.target, cv=3) #This is same as whole above code
#This will devidie data into 3fold corssing, and apply the model and get the result .But for only one model


array([0.96494157, 0.97996661, 0.96494157])

In [115]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target, cv=3) #This is same as whole above code
#This will devidie data into 3fold corssing, and apply the model and get the result .But for only one model

array([0.94156928, 0.94657763, 0.92487479])

In [116]:
cross_val_score(LogisticRegression(),digits.data,digits.target, cv=3) #This is same as whole above code
#This will devidie data into 3fold corssing, and apply the model and get the result .But for only one model

C:\Users\ZEESHAN123\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\ZEESHAN123\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#lo

array([0.92153589, 0.94156928, 0.91652755])